### ISSUE TITLE
Default value of UTIL_FUNCTION_ALIGNMENT not working when compiling for 64 bit

### ISSUE THREAD

**Issue by danielschenk** [philips-software/embeddedinfralib#27]
I'm building unit tests for code which uses infra functionality, using gcc on Linux which compiles for 64-bit by default. I noticed that [this assertion](https://github.com/philips-software/embeddedinfralib/blob/e2c734dd56c3551a78709feac2cee197498ddf95/infra/util/Function.hpp#L277) failed. I worked around it by overriding the define to `uint64_t` in my build.

Is there a specific reason that this is not handled automatically, for example by defining this to `void*`?

**Comment by rjaegers** [comment]
When using CCola, when a 64-bit platform is detected, the UTIL_FUNCTION_ALIGNMENT is set to `uin64_t` by CMake.

That being said, I think your suggestion is fair. Could you open a pull-request?
