### ISSUE TITLE
`std::result_of` has been deprecated in C++17 and removed in C++20. Replaced by `std::invoke_result`

### ISSUE THREAD

**Issue by daantimmer** [philips-software/embeddedinfralib#54]
`std::result_of` has, as of writing, 8 occurances in `infra/util/Observer.hpp`

Since C++17 a helper type has been added for `std::invoke_result`, named `std::invoke_result_t` removing the need of using `std::invoke_result<...>::type`

**Comment by daantimmer** [comment]
I take it we can close this issue

**Comment by rjaegers** [comment]
This has been fixed in modern-cmake, but is not (yet) part of develop. If that suits your needs then keep the issue closed. Otherwise you can leave it open until the fix lands in develop.
