### ISSUE TITLE
warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]

### ISSUE THREAD

**Issue by daantimmer** [philips-software/embeddedinfralib#56]
https://github.com/philips-software/embeddedinfralib/blob/11bb04457c0b116cf820e7b23f2d327293ea8b3b/infra/util/BoundedVector.hpp#L375

https://github.com/philips-software/embeddedinfralib/blob/11bb04457c0b116cf820e7b23f2d327293ea8b3b/infra/util/BoundedVector.hpp#L382

`position` is of type `std::size_t`, which is guaranteed to be `unsigned`. Comparing an unsigned with `>= 0` is always true.

Ergo, the expression can be reduce to simply `position < size()`

**Comment by rjaegers** [comment]
Fixed in modern-cmake #74.
