### ISSUE TITLE
unused variable 'node' in IntrusiveSet::erase

### ISSUE THREAD

**Issue by daantimmer** [philips-software/embeddedinfralib#72]
IntrusiveSet::erase(...)'s first declared variabl (`node`) is unused in the function. 

https://github.com/philips-software/embeddedinfralib/blob/57c5153b4f3dcae7bf25731c2d733b208d0b986b/infra/util/IntrusiveSet.hpp#L235

**Comment by rjaegers** [comment]
Fixed in modern-cmake #73.
