### ISSUE TITLE
infra::IntrusiveList<>(and others) wrongly accept temporary references when adding elements

### ISSUE THREAD

**Issue by zhmu** [philips-software/embeddedinfralib#84]
The documentation states: "Another approach for storing elements in a container is to not allocate additional storage for an object, but to make the user of a container responsible for storage allocation. [...] For instance, objects used in an infra::IntrusiveForwardList each have a next pointer, so that when the container keeps track of its first element it can enumerate all its elements by following the next pointer.".

To me, this implies you must use a non-temporary argument whenever adding it to any type of intrusive container.

To my surprise, the following code compiles. It does not work, however, resulting in a failing test:

```
TEST(IntrusiveListTest, Whoops)
{
    infra::IntrusiveList<ListInt> list;
    list.push_back({3});
    EXPECT_TRUE(list.has_element(3));
}
```

The same holds for the IntrusiveForwardList<>, which causes a segfault on my system (gcc version 10.2.1 20210110 (Debian 10.2.1-6)):

```
TEST(IntrusiveForwardListTest, Whoops)
{
    infra::IntrusiveForwardList<ForwardListInt> list;
    list.insert_after(list.begin(), {1});
    EXPECT_TRUE(list.has_element(1));
}
```

(I have not checked the other intrusive containers)

I was surprised to find that both `push_back` and `insert_after` take a `const_reference` type for their value argument. It does explain why the code compiles. I would argue this is wrong, though: they need to modify the argument due to the intrusive-ness of the container. It also explains why there are so many `const_cast`-s in the container implementation, which is rarely a good sign.

Thus, I'd recommend not using `const_reference` for functions that modify the element. This would cause the code above not to compile, which feels like a much better approach than using freed storage.

**Comment by rjaegers** [comment]
Hi Rink, thanks for your detailed issue report. We will look into it as soon as possible.
